-- MySQL Script generated by MySQL Workbench
-- Sat Mar 19 12:29:45 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema elcaliz_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema elcaliz_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `elcaliz_db` DEFAULT CHARACTER SET utf8 ;
USE `elcaliz_db` ;

-- -----------------------------------------------------
-- Table `elcaliz_db`.`groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elcaliz_db`.`groups` (
  `id` TINYINT(10) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elcaliz_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elcaliz_db`.`users` (
  `id` TINYINT(10) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `lastname` VARCHAR(100) NOT NULL,
  `dni` VARCHAR(100) NOT NULL,
  `address` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NULL,
  `image` VARCHAR(100) NOT NULL,
  `group_id` TINYINT(10) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `dni_UNIQUE` (`dni` ASC) ,
  UNIQUE INDEX `mail_UNIQUE` (`email` ASC) ,
  INDEX `fk_users_groups1_idx` (`group_id` ASC) ,
  CONSTRAINT `fk_users_groups1`
    FOREIGN KEY (`group_id`)
    REFERENCES `elcaliz_db`.`groups` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elcaliz_db`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elcaliz_db`.`products` (
  `id` TINYINT(10) NOT NULL AUTO_INCREMENT,
  `sku` VARCHAR(100) NULL,
  `name` VARCHAR(100) NULL,
  `description` TEXT NULL,
  `price` INT NULL,
  `discount` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `referencia_UNIQUE` (`sku` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elcaliz_db`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elcaliz_db`.`category` (
  `id` TINYINT(10) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elcaliz_db`.`products_has_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elcaliz_db`.`products_has_category` (
  `products_id` TINYINT(10) NOT NULL,
  `category_id` TINYINT(10) NOT NULL,
  PRIMARY KEY (`products_id`, `category_id`),
  INDEX `fk_products_has_category_category1_idx` (`category_id` ASC) ,
  INDEX `fk_products_has_category_products1_idx` (`products_id` ASC) ,
  CONSTRAINT `fk_products_has_category_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `elcaliz_db`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_has_category_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `elcaliz_db`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;