-- MySQL Script generated by MySQL Workbench
-- Tue Feb  8 15:25:26 2022
-- Model: New Model    Version: 1.0
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema elcaliz_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema elcaliz_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `elcaliz_db` DEFAULT CHARACTER SET utf8 ;
USE `elcaliz_db` ;

-- -----------------------------------------------------
-- Table `elcaliz_db`.`groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elcaliz_db`.`groups` (
  `id` TINYINT(10) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elcaliz_db`.`genres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elcaliz_db`.`genres` (
  `id` TINYINT(10) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elcaliz_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elcaliz_db`.`users` (
  `id` TINYINT(10) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `apellido` VARCHAR(100) NOT NULL,
  `dni` VARCHAR(100) NOT NULL,
  `mail` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NULL,
  `fecha_registro` DATE NULL,
  `estado` INT NULL,
  `image` VARCHAR(100) NOT NULL,
  `group_id` TINYINT(10) NOT NULL,
  `genre_id` TINYINT(10) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `dni_UNIQUE` (`dni` ASC) ,
  UNIQUE INDEX `mail_UNIQUE` (`mail` ASC) ,
  INDEX `fk_users_groups1_idx` (`group_id` ASC) ,
  INDEX `fk_users_genres1_idx` (`genre_id` ASC) ,
  CONSTRAINT `fk_users_groups1`
    FOREIGN KEY (`group_id`)
    REFERENCES `elcaliz_db`.`groups` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_genres1`
    FOREIGN KEY (`genre_id`)
    REFERENCES `elcaliz_db`.`genres` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elcaliz_db`.`states`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elcaliz_db`.`states` (
  `id` TINYINT(10) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elcaliz_db`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elcaliz_db`.`orders` (
  `id` TINYINT(10) NOT NULL AUTO_INCREMENT,
  `referencia` VARCHAR(100) NULL,
  `total` INT NULL,
  `metodo_pago` VARCHAR(100) NULL,
  `fecha` DATE NULL,
  `user_id` TINYINT(10) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_orders_users1_idx` (`user_id` ASC) ,
  CONSTRAINT `fk_orders_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `elcaliz_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elcaliz_db`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elcaliz_db`.`products` (
  `id` TINYINT(10) NOT NULL AUTO_INCREMENT,
  `sku` VARCHAR(100) NULL,
  `nombre` VARCHAR(100) NULL,
  `descripcion` TEXT NULL,
  `precio` INT NULL,
  `discount` INT NULL,
  `estado` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `referencia_UNIQUE` (`sku` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elcaliz_db`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elcaliz_db`.`categories` (
  `id` TINYINT(10) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  `value` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elcaliz_db`.`images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elcaliz_db`.`images` (
  `id` TINYINT(10) NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(100) NULL,
  `product_id` TINYINT(10) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_images_products1_idx` (`product_id` ASC) ,
  CONSTRAINT `fk_images_products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `elcaliz_db`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elcaliz_db`.`orders_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elcaliz_db`.`orders_status` (
  `id` TINYINT(10) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elcaliz_db`.`adresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elcaliz_db`.`adresses` (
  `id` TINYINT(10) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `apellido` VARCHAR(100) NOT NULL,
  `direccion` VARCHAR(100) NULL,
  `codigo_postal` VARCHAR(100) NULL,
  `localidad` VARCHAR(100) NULL,
  `telefono` INT NULL,
  `state_id` TINYINT(10) NOT NULL,
  `user_id` TINYINT(10) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_adresses_states1_idx` (`state_id` ASC) ,
  INDEX `fk_adresses_users1_idx` (`user_id` ASC) ,
  CONSTRAINT `fk_adresses_states1`
    FOREIGN KEY (`state_id`)
    REFERENCES `elcaliz_db`.`states` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_adresses_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `elcaliz_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elcaliz_db`.`products_has_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elcaliz_db`.`products_has_categories` (
  `productos_has_categorias_id` TINYINT(10) NOT NULL AUTO_INCREMENT,
  `product_id` TINYINT(10) NOT NULL,
  `category_id` TINYINT(10) NOT NULL,
  PRIMARY KEY (`productos_has_categorias_id`),
  INDEX `fk_products_has_categories_products1_idx` (`product_id` ASC) ,
  INDEX `fk_products_has_categories_categories1_idx` (`category_id` ASC) ,
  CONSTRAINT `fk_products_has_categories_products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `elcaliz_db`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_has_categories_categories1`
    FOREIGN KEY (`category_id`)
    REFERENCES `elcaliz_db`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elcaliz_db`.`orders_has_orders_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elcaliz_db`.`orders_has_orders_status` (
  `id` TINYINT(10) NOT NULL AUTO_INCREMENT,
  `fecha_estado` DATETIME NULL,
  `order_id` TINYINT(10) NOT NULL,
  `order_status_id` TINYINT(10) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_orders_has_orders_status_orders1_idx` (`order_id` ASC) ,
  INDEX `fk_orders_has_orders_status_orders_status1_idx` (`order_status_id` ASC) ,
  CONSTRAINT `fk_orders_has_orders_status_orders1`
    FOREIGN KEY (`order_id`)
    REFERENCES `elcaliz_db`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_has_orders_status_orders_status1`
    FOREIGN KEY (`order_status_id`)
    REFERENCES `elcaliz_db`.`orders_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elcaliz_db`.`products_has_orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elcaliz_db`.`products_has_orders` (
  `productos_has_pedidos_id` TINYINT(10) NOT NULL AUTO_INCREMENT,
  `id_pedido` TINYINT(10) NOT NULL,
  `precio` DECIMAL(10,2) UNSIGNED NULL,
  `cantidad` INT NULL,
  `product_id` TINYINT(10) NOT NULL,
  PRIMARY KEY (`productos_has_pedidos_id`),
  INDEX `fk_productos_has_pedidos_pedidos1_idx` (`id_pedido` ASC) ,
  INDEX `fk_products_has_orders_products1_idx` (`product_id` ASC) ,
  CONSTRAINT `fk_productos_has_pedidos_pedidos1`
    FOREIGN KEY (`id_pedido`)
    REFERENCES `elcaliz_db`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_has_orders_products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `elcaliz_db`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
