-- MySQL Script generated by MySQL Workbench
-- Wed Jan 26 19:36:37 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`groups` (
  `id(pk)` TINYINT(10) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  PRIMARY KEY (`id(pk)`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`genres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`genres` (
  `id(pk)` TINYINT(10) NOT NULL,
  `nombre` VARCHAR(100) NULL,
  PRIMARY KEY (`id(pk)`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id(pk)` TINYINT(10) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `apellido` VARCHAR(100) NOT NULL,
  `dni` VARCHAR(100) NOT NULL,
  `mail` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NULL,
  `fecha_registro` DATE NULL,
  `estado` INT NULL,
  `id_grupo(fk)` INT NOT NULL,
  `id_genero(fk)` INT NOT NULL,
  `image` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id(pk)`, `id_grupo(fk)`, `image`),
  UNIQUE INDEX `dni_UNIQUE` (`dni` ASC) VISIBLE,
  UNIQUE INDEX `mail_UNIQUE` (`mail` ASC) VISIBLE,
  INDEX `fk_clientes_grupos1_idx` (`id_grupo(fk)` ASC) VISIBLE,
  INDEX `fk_clientes_generos1_idx` (`id_genero(fk)` ASC) VISIBLE,
  CONSTRAINT `fk_clientes_grupos1`
    FOREIGN KEY (`id_grupo(fk)`)
    REFERENCES `mydb`.`groups` (`id(pk)`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_clientes_generos1`
    FOREIGN KEY (`id_genero(fk)`)
    REFERENCES `mydb`.`genres` (`id(pk)`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`states`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`states` (
  `id(pk)` TINYINT(10) NOT NULL,
  `nombre` VARCHAR(100) NULL,
  PRIMARY KEY (`id(pk)`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`orders` (
  `id(pk)` TINYINT(10) NOT NULL,
  `referencia` VARCHAR(100) NULL,
  `id_cliente(fk)` TINYINT(10) NOT NULL,
  `total` INT NULL,
  `metodo_pago` VARCHAR(100) NULL,
  `fecha` DATE NULL,
  PRIMARY KEY (`id(pk)`),
  INDEX `fk_pedidos_clientes1_idx` (`id_cliente(fk)` ASC) VISIBLE,
  CONSTRAINT `fk_pedidos_clientes1`
    FOREIGN KEY (`id_cliente(fk)`)
    REFERENCES `mydb`.`users` (`id(pk)`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`products` (
  `id(pk)` TINYINT(10) NOT NULL,
  `sku` VARCHAR(100) NULL,
  `nombre` VARCHAR(100) NULL,
  `descripcion` TEXT NULL,
  `precio` INT NULL,
  `discount` INT NULL,
  `estado` INT NULL,
  PRIMARY KEY (`id(pk)`),
  UNIQUE INDEX `referencia_UNIQUE` (`sku` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categories` (
  `id(pk)` TINYINT(10) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  `value` VARCHAR(100) NULL,
  PRIMARY KEY (`id(pk)`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`images` (
  `id(pk)` TINYINT(10) NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(100) NULL,
  `productos_idproductos(pk)` INT NOT NULL,
  PRIMARY KEY (`id(pk)`, `productos_idproductos(pk)`),
  INDEX `fk_imagenes_productos1_idx` (`productos_idproductos(pk)` ASC) VISIBLE,
  CONSTRAINT `fk_imagenes_productos1`
    FOREIGN KEY (`productos_idproductos(pk)`)
    REFERENCES `mydb`.`products` (`id(pk)`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`orders_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`orders_status` (
  `id(pk)` TINYINT(10) NOT NULL,
  `nombre` VARCHAR(100) NULL,
  PRIMARY KEY (`id(pk)`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`adresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`adresses` (
  `id(pk)` TINYINT(10) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `apellido` VARCHAR(100) NOT NULL,
  `direccion` VARCHAR(100) NULL,
  `codigo_postal` VARCHAR(100) NULL,
  `localidad` VARCHAR(100) NULL,
  `id_provincia(fk)` INT NOT NULL,
  `telefono` INT NULL,
  `clientes_id(fk)` INT NOT NULL,
  PRIMARY KEY (`id(pk)`, `id_provincia(fk)`),
  INDEX `fk_direcciones_provincias1_idx` (`id_provincia(fk)` ASC) VISIBLE,
  INDEX `fk_direcciones_clientes1_idx` (`clientes_id(fk)` ASC) VISIBLE,
  CONSTRAINT `fk_direcciones_provincias1`
    FOREIGN KEY (`id_provincia(fk)`)
    REFERENCES `mydb`.`states` (`id(pk)`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_direcciones_clientes1`
    FOREIGN KEY (`clientes_id(fk)`)
    REFERENCES `mydb`.`users` (`id(pk)`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`products_has_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`products_has_categories` (
  `productos_has_categorias_id(pk)` TINYINT(10) NOT NULL AUTO_INCREMENT,
  `id_producto(fk)` INT NOT NULL,
  `id_categoria(fk)` INT NOT NULL,
  PRIMARY KEY (`productos_has_categorias_id(pk)`, `id_producto(fk)`, `id_categoria(fk)`),
  INDEX `fk_productos_has_categorias_categorias1_idx` (`id_categoria(fk)` ASC) VISIBLE,
  INDEX `fk_productos_has_categorias_productos1_idx` (`id_producto(fk)` ASC) VISIBLE,
  CONSTRAINT `fk_productos_has_categorias_productos1`
    FOREIGN KEY (`id_producto(fk)`)
    REFERENCES `mydb`.`products` (`id(pk)`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_productos_has_categorias_categorias1`
    FOREIGN KEY (`id_categoria(fk)`)
    REFERENCES `mydb`.`categories` (`id(pk)`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`orders_has_orders_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`orders_has_orders_status` (
  `id(pk)` TINYINT(10) NOT NULL AUTO_INCREMENT,
  `id_pedido(fk)` TINYINT(10) NOT NULL,
  `id_estados_pedidos(fk)` TINYINT(10) NOT NULL,
  `fecha_estado` DATETIME NULL,
  PRIMARY KEY (`id(pk)`, `id_pedido(fk)`, `id_estados_pedidos(fk)`),
  INDEX `fk_pedidos_has_estados_pedidos_estados_pedidos1_idx` (`id_estados_pedidos(fk)` ASC) VISIBLE,
  INDEX `fk_pedidos_has_estados_pedidos_pedidos1_idx` (`id_pedido(fk)` ASC) VISIBLE,
  CONSTRAINT `fk_pedidos_has_estados_pedidos_pedidos1`
    FOREIGN KEY (`id_pedido(fk)`)
    REFERENCES `mydb`.`orders` (`id(pk)`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedidos_has_estados_pedidos_estados_pedidos1`
    FOREIGN KEY (`id_estados_pedidos(fk)`)
    REFERENCES `mydb`.`orders_status` (`id(pk)`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`products_has_orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`products_has_orders` (
  `productos_has_pedidos_id(pk)` TINYINT(10) NOT NULL,
  `id_pedido(fk)` TINYINT(10) NOT NULL,
  `id_producto(fk)` TINYINT(10) NOT NULL,
  `precio` DECIMAL(2) NULL,
  `cantidad` INT NULL,
  PRIMARY KEY (`productos_has_pedidos_id(pk)`),
  INDEX `fk_productos_has_pedidos_pedidos1_idx` (`id_pedido(fk)` ASC) VISIBLE,
  INDEX `fk_productos_has_pedidos_productos1_idx` (`id_producto(fk)` ASC) VISIBLE,
  CONSTRAINT `fk_productos_has_pedidos_productos1`
    FOREIGN KEY (`id_producto(fk)`)
    REFERENCES `mydb`.`products` (`id(pk)`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_productos_has_pedidos_pedidos1`
    FOREIGN KEY (`id_pedido(fk)`)
    REFERENCES `mydb`.`orders` (`id(pk)`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
